[tool.poetry]
<<<<<<< HEAD
name = "dataqualitycontrol"
version = "0.1.0"
description = ""
authors = ["giyash <ashimgiyanani@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.5.1"
matplotlib = "^3.6.1"
numpy = "^1.23.4"
scipy = "^1.9.3"
=======
name = "highre-mwe"
version = "0.1.0"
description = "minimum working example for HighRe data"
authors = ["Ashim Giyanani"]
license = "free"
readme = "README.md"
packages = [{include = "highre_mwe"}]

[tool.poetry.dependencies]
python = "^3.9"
ipykernel = "^6.17.1"
pandas = "^1.5.1"
matplotlib = "^3.6.2"
circle-fit = "^0.1.3"
plotly = "^5.11.0"
spyder = "5.4"
requests = "^2.28.1"
numpy = "^1.23.4"
suds = "^1.1.2"
sqlalchemy = "^1.4.43"
glob2 = "^0.7"
aiohttp = "^3.8.3"
spyder-kernels = "2.4.*"
>>>>>>> 427008e7b131de2ca58a1842add4494ff6e66972


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
